version: '2'
services:
  web:
    build: .
    ports:
      - "8082:8082"
  db:
    image: mysql:5.6
    build:
      context: ./mysql_docker
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=ooc_test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234